### PR TITLE
Replace `Array#filter` with `Array#count`

### LINKED ISSUE #10: 2.5 does not work: `Array#filter` was introduced in Ruby 2.6
Ref: https://github.com/ruby/ruby/blob/v2_6_0/NEWS

```
Aliased methods
Array#filter is a new alias for Array#select. [Feature #13784]
```

I'm going to switch to `Array#select`

### PR DESCRIPTION
**Pull request by tagliala**
`Array#filter` has been introduced in Ruby 2.6 as an alias of
`Array#select`.

Moreover, it is possible to use `Array#count` with a block instead
of filtering and counting

This commit switches to `Array#count` to fix Ruby 2.5 compatibility
and improve IPS and memory performance

```
%i[ips memory].each do |benchmark|
  Benchmark.send(benchmark) do |x|
    x.report('select') { [1,2,3].select { |d| d.odd? }.count }
    x.report('count') { [1,2,3].count { |d| d.odd? } }
    x.compare!
  end
end

Comparison (IPS):
               count:  6920204.9 i/s
              select:  5783214.4 i/s - 1.20x  (± 0.00) slower

Comparison (Memory):
               count:         40 allocated
              select:         80 allocated - 2.00x more
```

Close #10

---

Green build: https://github.com/tagliala/simplecov_lcov_formatter/actions/runs/13225194991

### CODE REVIEW

File: lib/simplecov_lcov_formatter.rb [hunk 1]
```diff
@@ -81,8 +81,8 @@ def format_file(file)
         pieces = []
         pieces << "SF:#{filename}"
         pieces << format_lines(file)
-        pieces << "LF:#{file.lines.filter { |el| el.coverage }.count}"
-        pieces << "LH:#{file.lines.filter { |el| el.coverage && el.coverage > 0 }.count}"
+        pieces << "LF:#{file.lines.select { |el| el.coverage }.count}"
+        pieces << "LH:#{file.lines.select { |el| el.coverage && el.coverage > 0 }.count}"
```
Comment (tagliala) [inline lib/simplecov_lcov_formatter.rb]: but if we need to count, we can use `Array#count` with a block:

https://ruby-doc.org/core-2.5.8/Array.html

**Comment by tagliala** [comment]
Rebased and ready for review

File: lib/simplecov_lcov_formatter.rb [hunk 2]
```diff
@@ -81,8 +81,8 @@ def format_file(file)
         pieces = []
         pieces << "SF:#{filename}"
         pieces << format_lines(file)
-        pieces << "LF:#{file.lines.filter { |el| el.coverage }.count}"
-        pieces << "LH:#{file.lines.filter { |el| el.coverage && el.coverage > 0 }.count}"
+        pieces << "LF:#{file.lines.count { |el| el.coverage }}"
+        pieces << "LH:#{file.lines.count { |el| el.coverage && el.coverage > 0 }}"
```
Comment (t-mario-y) [inline lib/simplecov_lcov_formatter.rb:85]: `docker pull ruby:2.5.9-slim-stretch` and checked under `irb`
```
irb(main):001:0> [1,2].methods.grep /filter/
=> []
irb(main):002:0> [1,2].methods.grep /select/
=> [:select!, :select]
irb(main):003:0> [1,2].methods.grep /count/
=> [:count]
irb(main):004:0> [1,2,3,1].count do |e| e==1 end
=> 2
```

**Review by t-mario-y — APPROVED** [review]
This is what I added and broken on old Ruby 2.5
Benchmark result is also fine

LGTM, thx!
